# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Deployment Github Action

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build_angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: |
            angular-chat/package-lock.json
      - name: Install and build Angular
        run: |
          cd angular-chat
          npm ci
          npm run build
  build_react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: |
            react-chat/package-lock.json
      - name: Install and build Angular
        run: |
          cd react-chat
          npm ci
          npm run build
  build_vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: |
            vue-chat/package-lock.json
      - name: Install and build Angular
        run: |
          cd vue-chat
          npm ci
          npm run build
